import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "@/components/shared/providers";
import { Header } from "@/widgets/Header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
            <Header />
            {children}
        </Providers>
      </body>
    </html>
  );
}
